spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/clinic'
    username: 'root'
    password: 'admin'

  mandatory-file-encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080